import requests
from bs4 import BeautifulSoup
import re
import os

# 目标URL列表
urls = [
    'https://monitor.gacjie.cn/page/cloudflare/ipv4.html', 
    'https://ip.164746.xyz'
]

# 正则表达式用于匹配IP地址
ip_pattern = r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'  # 添加了单词边界

# 请求头
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# 使用集合存储IP，自动去重
ip_set = set()

for url in urls:
    try:
        # 发送HTTP请求获取网页内容
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()  # 检查请求是否成功
        
        # 使用BeautifulSoup解析HTML
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # 统一查找tr元素
        elements = soup.find_all('tr')
        
        # 遍历所有元素,查找IP地址
        for element in elements:
            element_text = element.get_text()
            ip_matches = re.findall(ip_pattern, element_text)
            ip_set.update(ip_matches)  # 添加到集合中
            
    except requests.exceptions.RequestException as e:
        print(f"请求 {url} 时出错: {e}")
        continue

# 写入文件
with open('ip.txt', 'w') as file:
    for ip in sorted(ip_set):  # 排序后写入
        file.write(ip + '\n')

print(f'找到 {len(ip_set)} 个唯一IP地址，已保存到ip.txt文件中。')
