name: Update IP List

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/collect_ips.py') }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip pip-tools
        echo "requests==2.31.0" > constraints.txt
        echo "beautifulsoup4==4.12.0" >> constraints.txt
        pip install -c constraints.txt requests beautifulsoup4

    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py || exit 1

    - name: Verify IP list
      run: |
        if [ ! -s ip.txt ]; then
          echo "Error: IP list is empty or missing"
          exit 1
        fi

    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "tianshideyou@proton.me"
        git config --global user.name "tianshipapa"
        git add ip.txt
        git commit -m "Update IP list"  # 移除了时间戳
        git push origin HEAD
